### ISSUE TITLE
New performance metrics

### ISSUE THREAD

**Issue by j-fletcher** [j-fletcher/barc_blanket#27]
DPA rate in vacuum vessel
total mass of the waste in case 4
Time to class C (TTCC) for each of the 4 cases we mentioned--see if our "10%" of the blanket volume is really accurate, given that maintenance team is operating with a FLiBe volume on the order of 700 m3. The way this should be calculated is by quantifying the TTCC for the 10% loading into the FLiBe--this gives us the FPY needed to burn that mass of the tank contents. Then we can take the reciprocal to find kg per FPY
Magnet fast flux and heating? Or is DPA the more appropriate metric
Lithium depletion rate over the ~60 year timeline
TBR with waste loading--can we go to higher waste loading? This is probably more limited by the solubility, but vitrifying is outrunning us by virtue of them containing 400m3 per year while we do 70 m3 per 60 years
k in blanket without actinides removed

**Comment by jo-hall** [comment]
- Don't know how to find the DPA rate in the vaccuum vessel, I imagine that's some complicated experimental dependence on neutron fluence, which is easy to calculate.
- Same thing with magnet flux
- Lithium depletion and oxygenation can probably both be fixed by adding transfer rates to the depletion integrator. I am testing this out tonight (monday) for oxygen, but I think it needs to be done more carefully with the Li. To be honest, the change in Li6/Li7 fraction is so small (changes by 2% over 100 years) that I think we can ignore it. If anything, it's good because we get more Li6 over time.
- We need to look at TBR over time with the new enrichments. I'm working on that now also

Haven't done anything on magnet flux. Stefano Segantin has sample code for this I can find next time we meet

**Comment by j-fletcher** [comment]
Add a damage-energy tally then use KP to find DPA--make sure to tally by target element for all those within the VV material. FISPACT manual has displacement energies

**Comment by j-fletcher** [comment]
Get also total volume of waste for each of the discussed cases--this is the total volume of material taken from the tanks, not necessarily what is put into the flibe
